### ISSUE TITLE
Configurable snapshot tags

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-orchestrator#2]
When Orchestrator creates a snapshot, it should copy the tags from the EC2 instance it's taking the snapshot from.

Orchestrator's application.properties need to have a new configuration for a comma-separated tag names.
Default value for this config: `Component,Name,StackPrefix` .

Orchestrator should also add a tag `SnapshotType` with value `orchestration`.
This is used to distinguish the retention policy between various snapshot types.

**Comment by cliffano** [comment]
Has the `SnapshotType=orchestration` been included?
This tag can't be copied from the instance as this is specific to snapshot and is created by the Orchestrator.

**Comment by nletts** [comment]
Nice pick up. The `SnapshotType=orchestration` has now been added.
